# Generated by Django 4.2.1 on 2023-06-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_1',
            field=models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], default='NE', max_length=255),
        ),
    ]
